# Generated by Django 6.0.1 on 2026-01-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "profile_path",
                    models.URLField(blank=True, null=True, verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name": "Актёр",
                "verbose_name_plural": "Актёры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("overview", models.TextField(verbose_name="Описание")),
                (
                    "poster_path",
                    models.URLField(blank=True, null=True, verbose_name="Постер"),
                ),
                (
                    "backdrop_path",
                    models.URLField(blank=True, null=True, verbose_name="Фон"),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="Рейтинг")),
                ("release_date", models.DateField(verbose_name="Дата выхода")),
                (
                    "vote_count",
                    models.IntegerField(default=0, verbose_name="Количество голосов"),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movies", to="movies.genre", verbose_name="Жанры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="MovieCast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.CharField(max_length=255, verbose_name="Персонаж"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.actor",
                        verbose_name="Актёр",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast",
                        to="movies.movie",
                        verbose_name="Фильм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Актёрский состав",
                "ordering": ["order"],
            },
        ),
    ]
