# Generated by Django 6.0.1 on 2026-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="actors/",
                verbose_name="Фото (загрузка)",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="backdrop_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="backdrops/",
                verbose_name="Фон (загрузка)",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posters/",
                verbose_name="Постер (загрузка)",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="profile_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Фото (URL или путь)",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Фон (URL или путь)"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Постер (URL или путь)",
            ),
        ),
    ]
