# Generated by Django 6.0.1 on 2026-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_actor_profile_image_movie_backdrop_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kinopoisk_api_token",
                    models.CharField(
                        blank=True,
                        help_text="Получите токен на https://kinopoiskapiunofficial.tech",
                        max_length=255,
                        null=True,
                        verbose_name="Kinopoisk API токен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки",
                "verbose_name_plural": "Настройки",
            },
        ),
    ]
