# Generated by Django 6.0.1 on 2026-01-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="kinopoisk_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Кинопоиск ID"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="age_rating",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Возрастной рейтинг"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="film_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Продолжительность (мин)"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="IMDb ID"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="kinopoisk_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Кинопоиск ID"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="name_original",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Оригинальное название",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="slogan",
            field=models.TextField(blank=True, null=True, verbose_name="Слоган"),
        ),
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Тип (FILM, TV_SHOW и т.д.)",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                to="movies.country",
                verbose_name="Страны",
            ),
        ),
        migrations.CreateModel(
            name="MovieSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название источника"),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание/Инструкция"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="movies.movie",
                        verbose_name="Фильм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
                "ordering": ["created_at"],
            },
        ),
    ]
