# Generated by Django 6.0.1 on 2026-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_country_actor_kinopoisk_id_movie_age_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на трейлер"
            ),
        ),
    ]
